#pragma once
#include <Windows.h>

#define  DESKTOP_ALL ( DESKTOP_READOBJECTS |  DESKTOP_CREATEWINDOW |  \
DESKTOP_CREATEMENU |  DESKTOP_HOOKCONTROL |  DESKTOP_JOURNALRECORD |  \
DESKTOP_JOURNALPLAYBACK |  DESKTOP_ENUMERATE |  DESKTOP_WRITEOBJECTS |  \
DESKTOP_SWITCHDESKTOP |  STANDARD_RIGHTS_REQUIRED)

#define WINSTA_ALL ( WINSTA_ENUMDESKTOPS |  WINSTA_READATTRIBUTES |  \
WINSTA_ACCESSCLIPBOARD |  WINSTA_CREATEDESKTOP |  WINSTA_WRITEATTRIBUTES |  \
WINSTA_ACCESSGLOBALATOMS |  WINSTA_EXITWINDOWS |  WINSTA_ENUMERATE |  \
WINSTA_READSCREEN |  STANDARD_RIGHTS_REQUIRED)

#define GENERIC_ACCESS ( GENERIC_READ |  GENERIC_WRITE |  GENERIC_EXECUTE |  GENERIC_ALL)

BOOL AddAceToWindowStation(HWINSTA hwinsta, PSID psid);

BOOL AddAceToDesktop(HDESK hdesk, PSID psid);

BOOL GetLogonSID(HANDLE hToken, PSID * ppsid);

VOID FreeLogonSID(PSID * ppsid);

BOOL StartInteractiveClientProcess(
	LPTSTR lpszUsername,     // client to log on
	LPTSTR lpszDomain,      // domain of client's account
	LPTSTR lpszPassword,    // client's password
	LPTSTR lpCommandLine    // command line to execute
);