#pragma once

#define J_newScan "newScan"
#define J_replaceScan "replaceScan"
#define J_insertScan "insertScan"
#define J_packageImages "packageImages"
#define J_perviousImage "perviousImage"
#define J_nextImage "nextImage"
#define J_SaveConifg "SaveConifg"
#define J_LoadConfig "LoadConfig"
#define J_clearScan "clearScan"
#define J_deleteImage "deleteImage"
#define J_uploadFile "uploadFile"
#define J_getFileIndex "getFileIndex"
#define J_adjustFile "adjustFile"
#define J_getCurrentIndex "getCurrentIndex"
#define J_getFileCount "getFileCount"
#define J_setScanFolder "setScanFolder"
#define J_getFileList "getFileList"
#define J_setCurrentIndex "setCurrentIndex"
#define J_getFileInfo "getFileInfo"
#define J_insertExternalFile  "insertExternalFile"
#define J_getFileFullName "getFileFullName"
#define J_getDeviceList "getDeviceList"
#define J_setDefaultDevice "setDefaultDevice"
#define J_getDefaultDevice "getDefaultDevice"
#define J_replaceCurrentFile "replaceCurrentFile"
#define J_insertExternalFiles "insertExternalFiles"
